### ISSUE TITLE
Make hired people in the new menu instead?

### ISSUE THREAD

**Issue by insomnius** [rizafahmi/carikerja#26]
**Current condition**

Hired people listed in the same pages as the job seeker one.

**What i suggest**

Make it in the new menu to make better exposure for the job seeker

**What to do**

Create a new menu for a hired people? Or maybe some filter to filter only job seeker?

**Comment by naptr** [comment]
apakah bantuan masih dibutuhkan?

**Comment by rizafahmi** [comment]
Masih. Silakan di claim dan lakukan PR. Terimakasih
